### ISSUE TITLE
skip plugins is set as true

### ISSUE THREAD

**Issue by anshumandas** [Rebilly/swagger-repo#11]
Hi
Thanks for this excellent project that you have open sourced.
i would like to use it and extend it for a tool that I am building.

In your index.js file the swaggerEditorMiddleware part has **skipPlugins: true**
Is there a way to override this?
Could you allow for some configuration here.

Thanks
Anshuman Das

**Comment by RomanHotsiy** [comment]
It can't be done.

If plugins are enabled and you save the file in the swagger editor we destructure the whole spec into components and save back to disc. And the issue is we won't be able to undo plugin changes to the spec.
