### ISSUE TITLE
New version breaks when not using basedir

### ISSUE THREAD

**Issue by felzan** [Rebilly/swagger-repo#17]
I was getting this error:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
In this new version the Path join is using the options basedir (in this line (https://github.com/Redocly/swagger-repo/commit/209f82779a5b8fded82d93a3f84cb50350ede2ba#diff-6d186b954a58d5bb740f73d84fe39073R306)) which is not the default command *"build": "swagger-repo build -o web_deploy"*

To make it run must use the *-b* option. Like this
**swagger-repo build -o web_deploy -b spec**

**Comment by RomanHotsiy** [comment]
Fixed in beta.13
