### ISSUE TITLE
Possibility of specifying the order in which paths are loaded

### ISSUE THREAD

**Issue by leonelgalan** [Rebilly/swagger-repo#5]
I just started using _Rebilly/generator-openapi-repo_ (you guys have done a great job!) and noticed that paths are loaded in alphabetical order. Is there any way we could customize that order?

**Comment by RomanHotsiy** [comment]
Hey @leonelgalan, thanks for your kind words ❤️ 

Unfortunately, there is no mechanism for this yet. Maybe ordering will become the part of ReDoc itself. Check out this PR: https://github.com/Rebilly/ReDoc/pull/328

But I'm eager to hear maybe some alternative ideas of how to achieve this!

**Comment by leonelgalan** [comment]
That PR looks promising, I'll keep and eye on it.
